MyFinance/Controllers/PlanoContaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFinance.Controllers
{
    public class PlanoContaController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public PlanoContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            PlanoContaModel objConta = new PlanoContaModel(HttpContextAccessor); //Objeto do tipo PlanoConta
            ViewBag.ListaPlanoConta = objConta.ListaPlanoConta();
            return View();
        }

        [HttpPost]
        public IActionResult CriarPlanoConta(PlanoContaModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }
            return View(formulario);
        }

        [HttpGet]
        public IActionResult CriarPlanoConta(int? id)
        {
            if (id != null)
            {
                PlanoContaModel objPlanoConta = new PlanoContaModel(HttpContextAccessor);
                ViewBag.Registro = objPlanoConta.CarregarRegistro(id);
            }
            return View();
        }



        public IActionResult ExcluirPlanoConta(int id)
        {
            PlanoContaModel objConta = new PlanoContaModel(HttpContextAccessor);
            objConta.Excluir(id);
            return RedirectToAction("Index");
        }

        
    }
}

MyFinance/Views/PlanoConta/CriarPlanoConta.cshtml
@model PlanoContaModel

@{ 
    var vId = 0;
    var vDescricao = "";
    var vTipo = "";

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vDescricao = @ViewBag.Registro.Descricao.ToString();
        vTipo = @ViewBag.Registro.Tipo.ToString();
    }
    catch (Exception ex)
    {
        
    }
}

<h3>Criar novo Plano de Conta</h3>

<form asp-controller="PlanoConta" asp-action="CriarPlanoConta">
    <input type="hidden" asp-for="Id" value="@vId" />
    <div class="form-group">
        <label>Descrição: </label>
        <input type="text" class="form-control" asp-for="Descricao" value="@vDescricao">
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <label>Tipo: </label>
        @{
            if (vTipo == "R")
            {
                <div class="radio">
                    <label><input type="radio" asp-for="Tipo" value="R" checked>Receita</label>
                    <label><input type="radio" asp-for="Tipo" value="D" unchecked>Despesa</label>
                </div>
            }
            else
            {
                <div class="radio">
                    <label><input type="radio" asp-for="Tipo" value="R" unchecked>Receita</label>
                    <label><input type="radio" asp-for="Tipo" value="D" checked>Despesa</label>
                </div>

            }
        }


    </div>
    <button type="submit" class="btn btn-block btn-success">Salvar</button>


</form>

MyFinance/Views/PlanoConta/Index.cshtml
<h3>Planos de conta</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>#</th>
            <th>ID</th>
            <th>DESCRICAO</th>
            <th>TIPO</th>
        </tr>
    </thead>
    @{
        foreach (var item in (List<PlanoContaModel>)ViewBag.ListaPlanoConta)
        {
            <tbody>
                <tr>
                    <td><button class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                    <td><button class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                    <td>@item.Id.ToString()</td>
                    <td>@item.Descricao.ToString()</td>
                    <td>@item.Tipo.ToString().Replace("R","Receita").Replace("D","Despesa")</td>
                </tr>
            </tbody>
        }
    }
</table>
<button type="button" class="btn btn-primary" onclick="window.location.href = '../PlanoConta/CriarPlanoConta'">Criar Plano de Conta</button>

<script>
    function Excluir(id_conta)
    {
        window.location.href = "../PlanoConta/ExcluirPlanoConta/" + id_conta;
    }

    function Editar(id_conta) {
        window.location.href = "../PlanoConta/CriarPlanoConta/" + id_conta;
    }
</script>