MyFinance/Controllers/ContaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyFinance.Models;
using Microsoft.AspNetCore.Http;

namespace MyFinance.Controllers
{
    public class ContaController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public ContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            ContaModel objConta = new ContaModel(HttpContextAccessor); //Objeto do tipo Conta
            ViewBag.ListaConta = objConta.ListaConta();
            return View();
        }

        [HttpPost]
        public IActionResult CriarConta(ContaModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }
            return View(formulario);
        }

        [HttpGet]
        public IActionResult CriarConta()
        {

            return View();
        }


        
        public IActionResult ExcluirConta(int id)
        {
            ContaModel objConta = new ContaModel(HttpContextAccessor);
            objConta.Excluir(id);
            return RedirectToAction("Index");
        }

    }
}

MyFinance/Views/Conta/CriarConta.cshtml
@model ContaModel

<h3>Criar nova conta</h3>

<form asp-controller="Conta" asp-action="CriarConta">
    <div class="form-group">
        <label for="nome">Nome: </label>
        <input type="text" class="form-control" asp-for="Nome">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Data_Nascimento">Saldo: </label>
        <input type="number" class="form-control" asp-for="Saldo">
        <span asp-validation-for="Saldo" class="text-danger"></span>
    </div>
    
    <button type="submit" class="btn btn-block btn-success">Salvar</button>


</form>

MyFinance/Views/Conta/Index.cshtml
<h3>Minhas contas</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>ID</th>
            <th>NOME</th>
            <th>SALDO</th>
        </tr>
    </thead>
    @{
        foreach (var item in (List<ContaModel>)ViewBag.ListaConta)
        {
            <tbody>
                    <tr>
                        <td><button class="btn btn-danger"  onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                        <td>@item.Id.ToString()</td>
                        <td>@item.Nome.ToString()</td>
                        <td>@item.Saldo.ToString()</td>
                    </tr>
            </tbody>
        }
    }
</table>
<button type="button" class="btn btn-primary" onclick="window.location.href = '../Conta/CriarConta'">Criar Conta</button>

<script>
    function Excluir(id_conta)
    {
        window.location.href = "../Conta/ExcluirConta/" + id_conta;
    }
</script>